### ISSUE TITLE
Foo_$1.yaml causes Script not found

### ISSUE THREAD

**Issue by jayvdb** [JoshMcguigan/cargo-run-script#5]
I have a script which looks like
```toml
[package.metadata.scripts]
foo = """
cargo run -p package_x -- bar --file ../../baz/Foo_$1.yaml
"""
```

This results in
```
thread 'main' panicked at /home/jayvdb/.cargo/registry/src/index.crates.io-6f17d22bba15001f/cargo-run-script-0.2.0/src/main.rs:44:18:
Script not found
```

When I remove `$1`, the script runs as expected.
